config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get 'about', to: 'pages#about'
  resources :articles
  get 'signup', to: 'users#new'
  post 'users', to: 'users#create'
  resources :users, except: [:new]
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  # resources :articles, only: [:show, :index, :new, :create, :edit, :update, :destroy]
  
  get "up" => "rails/health#show", as: :rails_health_check
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  validates :title, presence: true, length: {minimum: 6, maximum: 100}
  validates :description, presence: true, length: {minimum: 10, maximum: 300}
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email = email.downcase }
  has_many :articles, dependent: :destroy
  validates :username, presence: true, 
                       uniqueness: { case_sensitive: false },
                       length: { minimum: 3, maximum: 25 }

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i                     
  validates :email, presence: true, 
                    uniqueness: { case_sensitive: false }, 
                    length: { maximum: 105 },
                    format: { with: VALID_EMAIL_REGEX }

  has_secure_password                  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
 
  def logged_in?
    !!current_user
  end

  def require_user
    if !logged_in?
      flash[:alert] = "You must be logged in to perform that action."
      redirect_to login_path
    end
  end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  before_action :require_user, except: [:show, :index]
  before_action :require_same_user, only: [:edit, :update, :destroy]


  def show
    # byebug
    # @article = Article.find(params[:id])
  end

  def index
    @articles = Article.paginate(page: params[:page], per_page: 5)
  end

  def new
    @article = Article.new
  end

  def edit
    # @article = Article.find(params[:id])
  end

  def create
    @article = Article.new(article_params)
    @article.user = current_user
    if @article.save
      flash[:notice] = "Article was created successfully."
      redirect_to @article
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    # @article = Article.find(params[:id])
    if @article.update(article_params)
      flash[:notice] = "Article was updated successfully."
      redirect_to @article
    else
      render :edit,  status: :unprocessable_entity 
    end
  end

  def destroy
    # @article = Article.find(params[:id])
    @article.destroy
    redirect_to articles_path
  end

  private
  def set_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :description)
  end

  def require_same_user
    if current_user != @article.user && !current_user.admin?
      flash[:alert] = "You can only edit or delete your own article"
      redirect_to @article
    end
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    redirect_to articles_path if logged_in?
  end

  def about 
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:notice] = "Logged in successfully."
      redirect_to user
    else
      flash.now[:alert] = "There was something wrong with your login details"
      render 'new', status: :unprocessable_entity
    end
  end 

  def destroy
    session[:user_id] = nil
    flash[:notice] = "Logged out !"
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :require_user, only: [:edit, :update]
  before_action :require_same_user, only: [:edit, :update, :destroy]


  def new
    @user = User.new
  end

  def show
    @articles = @user.articles.paginate(page: params[:page], per_page: 5)
  end

  def index
    @users = User.paginate(page: params[:page], per_page: 5)
  end  
  
  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = "Welcome to the Alpha Blog #{@user.username}, you have successfully signed up."
      redirect_to articles_path
    else
      render 'new', status: :unprocessable_entity
    end    
  end
  
  def edit
  end  

  def update 
    if @user.update(user_params)
      flash[:notice] = "Your account information was successfully updated"
      redirect_to @user
    else
      render 'edit', status: :unprocessable_entity
    end  
  end

  def destroy
    @user.destroy
    session[:user_id] = nil if @user == current_user
    flash[:notice] = "Account and all associated articles successfully deleted."
    redirect_to articles_path
  end
  
  private 
  def user_params
    params.require(:user).permit(:username, :email, :password)
  end 
  
  def set_user
    @user = User.find(params[:id])
  end

  def require_same_user
    if current_user != @user && !current_user.admin?
      flash[:alert] = "You can only edit or delete your own account !"
      redirect_to @user
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def gravatar_for(user, options = { size: 80})
    email_address = user.email.downcase
    hash = Digest::MD5.hexdigest(email_address)
    size = options[:size]
    gravatar_url = "https://www.gravatar.com/avatar/#{hash}?s=#{size}"
    image_tag(gravatar_url, alt: user.username, class: "rounded shadow mx-auto d-block")
  end  
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/_article.html.erb
<table>
    <thead>
        <tr>
            <th>Title</th>
            <th>Description</th>
            <th>User</th>
            <th colspan="3">Actions</th>
        </tr>
    </thead>
    <tbody>
        <% @articles.each do |article| %>
            <tr>
                <td><%= article.title %></td>
                <td><%= article.description %></td>
                <% if article.user %>
                  <td><%= link_to article.user.username, user_path(article.user) %></td>
                <% end %>
                <td><%= link_to 'Show', article_path(article) %></td>
                <% if logged_in? && (article.user == current_user || current_user.admin?) %>
                 <td><%= link_to 'Edit', edit_article_path(article) %></td>
                 <td><%= link_to 'Delete', article_path(article), data: { "turbo-method": :delete , "turbo-confirm": "Are you sure?"} %></td>
                <% end %> 
            </tr>
        <% end %>
    </tbody>
</table>     

app/views/articles/_form.html.erb
<%= render 'shared/errors', obj: @article %>

 
<%= form_with(model: @article, local: true) do |f| %>
  <p> 
    <%= f.label :title %><br/> 
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :description %><br/> 
    <%= f.text_area :description %> 
  </p>
  <p>
    <%= f.submit %> 
  </p>
<% end %>

app/views/articles/edit.html.erb
<h1>Edit article</h1>

<%= render 'form' %>

<%= link_to 'Cancel and return to articles listing', articles_path %>

app/views/articles/index.html.erb
<h1>Articles Listing Page</h1>
<% if logged_in? %>
    <p>
      <%= link_to 'Create New Article', new_article_path %></td>
    </p>
 <% end %>   

<div class="flickr_pagination">
    <%= will_paginate @articles, :container => false %>
</div>

<%= render 'article' %>

<div class="flickr_pagination">
    <%= will_paginate @articles, :container => false %>
</div>

app/views/articles/new.html.erb
<h1>Create a new article</h1>

<%= render 'form' %>

<%= link_to 'Return to articles listing', articles_path %>

app/views/articles/show.html.erb
<h1>Showing articles details</h1>

<p><Strong>Title: </Strong><%=@article.title%></p>
<p><Strong>Description: </Strong><%=@article.description%></p>
<p><Strong>User: </Strong><%=@article.user.username if @article.user %></p>
<%= link_to gravatar_for(@article.user), user_path(@article.user) %>
<br/>
<br/>

<% if logged_in? && (@article.user == current_user || current_user.admin?) %>
    <%= link_to 'Edit', edit_article_path(@article) %> |
    <%= link_to 'Delete', article_path(@article), data: { "turbo-method": :delete , "turbo-confirm": "Are you sure?"} %> |
<% end %>
<%= link_to 'Return to articles listing', articles_path  %>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
   <%= msg %>
<% end %>   

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlphaBlog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'layouts/messages' %> 
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>This is about page</h2>

<%= link_to 'Articles listing', articles_path %> |
<%= link_to 'Home Page', root_path %>

app/views/pages/home.html.erb
<h1>This is home page</h1>

<%= link_to 'Articles listing', articles_path %> |
<%= link_to 'About Page', about_path %> |
<%= link_to "Bloggers", users_path %>
<br/>
<br/>
<% if logged_in? %>
  <%= "(Admin)" if current_user.admin? %><%= link_to current_user.username, user_path(current_user) %>
  <%= link_to "Logout!", logout_path, data: { turbo_method: :delete } %>
<% else %>
  <%= link_to "Log in!", login_path %>
  <%= link_to "Sign Up!", signup_path %>
<% end %>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <h2>The following errors prevented the <%= obj.class.name.downcase %> from being saved</h2>
    <ul>
        <% obj.errors.full_messages.each do |msg| %>
         <li> <%= msg %></li>
        <% end %>
    <ul>
<% end %> 

app/views/users/_form.html.erb
<%= render 'shared/errors', obj: @user %>
 
<%= form_with(model: @user, local: true) do |f| %>
  <p> 
    <%= f.label :username %><br/> 
    <%= f.text_field :username %>
  </p>
  <p>
    <%= f.label :email %><br/> 
    <%= f.email_field :email %> 
  </p>
  <p>
    <%= f.label :password %><br/> 
    <%= f.password_field :password %> 
  </p>
  <p>
    <%= f.submit(@user.new_record? ? "Sign Up" : "Update Account") %> 
  </p>
<% end %>

app/views/users/edit.html.erb
<br/>
<br/>
<%= link_to "Logout!", logout_path, data: { turbo_method: :delete } %>
<br/>
<br/>

<h1>Edit your profile</h1>

<%= render 'form' %>

<%= link_to 'Return to articles listing', articles_path %>

app/views/users/index.html.erb
<br/>
<br/>
<%= link_to "Logout!", logout_path, data: { turbo_method: :delete } %>
<br/>
<br/>

<%= link_to "Bloggers", users_path %>
<h1>Alpha Bloggers</h1>

<p>
  <%= link_to 'Create New Article', new_article_path %></td>
</p>

<div class="flickr_pagination">
    <%= will_paginate @users, :container => false %>
</div>

<table>
    <thead>
        <tr>
            <th>Profile</th>
            <th>Article Count</th>
            <th>User</th>
            <th colspan="3">Actions</th>
        </tr>
    </thead>
    <tbody>
        <% @users.each do |user| %>
            <tr>
                <td><%= link_to gravatar_for(user, size: 150), user %></td>
                <td><%= pluralize(user.articles.count, "article") %></td>
                <td><%= link_to user.username, user %></td>
                <td><%= link_to 'View Profile', user %></td>
                <% if logged_in? %>
                  <% if user == current_user %>
                    <td><%= link_to 'Edit Profile', edit_user_path(user) %></td>
                  <% end %>
                  <% if current_user.admin? || (user == current_user) %>
                    <td><%= link_to "Delete profile", user_path(user), data: { "turbo-method": :delete , "turbo-confirm": "Are you sure?"} %></td>
                   <% end %>  
                <% end %>  
                <td><small>Joined <%= time_ago_in_words(user.created_at) %>ago</small></td>
            </tr>
        <% end %>
    </tbody>
</table>     

<div class="flickr_pagination">
    <%= will_paginate @users, :container => false %>
</div>
   

app/views/users/new.html.erb
<h1>Sign Up for Alpha Blog</h1>

<%= render 'form' %>

app/views/users/show.html.erb
<br/>
<br/>
<%= link_to "Logout!", logout_path, data: { turbo_method: :delete } %>
<br/>
<br/>

<%= link_to "Bloggers", users_path %>


<h1><%= "(Admin)" if @user.admin? %><%= @user.username %>'s profile</h1>

<%= gravatar_for @user, size: 200 %>

<% if logged_in? && @user==current_user %>
    <div>
        <%= link_to "Edit your Profile", edit_user_path(@user) %>
    </div>    
<% end %>

<br/>
<%= link_to 'Return to articles listing', articles_path %>


<h3>Articles</h3>

<%= render 'articles/article' %>